### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by FavioGalvis** [BenjaminHae/seeddms-git#2]
Hey Bejamin, grettings.

I was going to make a repo of seeddms but i see you got the latest version already going, i got some issues with the installation.

Do you wanna work on this proyect with me?

**Comment by BenjaminHae** [comment]
Hi,
you mean installation of my extension, or installation of SeedDMS?
If you have problems installing my modifications I'd be interested to know.

I had a lot of problems setting the right permissions for the git repository, so I'm planning to drop the use of git in favor of plain rsync.

**Comment by FavioGalvis** [comment]
Hi Benjamin, 
I figured out the installation (some pear packages issues), no big deal, but i want to enhance the use of SeedDMS to scanners (any scanner hardware) directly from the web page, rigth now i am trying to understand how the Twain Spec. works, but im still learning.

The point is that maybe we can work together on this, since i dont see any develpment being done here, and all of the scanning to web DMS is paid.

The twain spec can be found here: http://www.twain.org/docs/530fe0da85f7511c510004ff/TWAIN-2.3-Spec.pdf

There is supposed to be a TwainDirect library for easy scanning software setup in early development but its closed alpha, and has been like that for almost a year.

**Comment by BenjaminHae** [comment]
just to make sure: I'm not the developer of seeddms(for reference http://sourceforge.net/projects/seeddms/ is the original location)!

I think your idea should be done independently of seeddms. You could automate scanning and entering information for your document. After that you can use utils/adddoc.php for automating insertion into seeddms.

**Comment by FavioGalvis** [comment]
Yes, you could use an intermediate software installed in the computer to scanne the document and then upload it to seeddms, but look it this way:

> User A has new computer on the office network and need to scan and index a documento to seedDMS, does he have to install software for that? its independent from the web page? why include 2 more steps in the routine of work of X users?
> Can the software be used in mutiple OS? why dont integrate in multi-browser?

The way I see it, there is no innovation if you simply put another software and you make more work where you should help reduce it.

edit: yes i know you are not the main developper, but he seems to be in a hiatus

**Comment by BenjaminHae** [comment]
I think it's not worth it to learn how to use twain etc. when it already works for me.
Sorry.
